[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "d7588f6"
hash = "3cce60031b27cbce80b50f68ca319c0a"

[[flavor.deps]]
use = "956MB/vscode-dark-modern"
rev = "cd60541"
hash = "d1134a80fdf8df043b2497846f137f04"
